// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Messenger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("Messenger.Models.MessageModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("fromUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FromUserId");

                    b.Property<DateTime>("messageSentTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("MessageSentTime");

                    b.Property<string>("messageText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MessageText");

                    b.Property<int>("toUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ToUserId");

                    b.HasKey("id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Messenger.Models.UserModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("hashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HashedPassword");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
